### ISSUE TITLE
ProfileScreen

### ISSUE THREAD

**Issue by NguyenNhatKhuongDuy2180602081** [IzumiDKC/Fashion-Shop-App#61]
Trang profile hiện đang không hiển thị thông tin người dùng mà chỉ load "Đang tải dữ liệu"

**Comment by IzumiDKC** [comment]
Đã xác định nguyên nhân!

**Comment by IzumiDKC** [comment]
Do vấn đề     [Authorize] cần xác thực khi chuyển trang, tạm thời xóa     [Authorize] ở AccountController ở .net
